<?php

/**
 * Test class for yFileInput.
 * Generated by PHPUnit on 2011-03-26 at 06:23:43.
 */
class yFileInputTest extends PHPUnit_Framework_TestCase{
    /**
     * @var yFileInput
     */
    protected $object;
    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(){
        
    }
    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(){
        
    }
    /**
     * @covers yFileInput
     */
    public function testAll(){
        $input = new yFileInput('file');
        $this->assertEquals('<input type="file" id="file" name="file" value="">', strval($input));
        $_FILES['file'] = array(
            'tmp_name'=>'tmp1',
            'name'=>'img.png',
        );
        $input->setKey(null);
        $input->processKey();
        $this->assertEquals('<input type="file" id="file" name="file" value="">', strval($input)); // value has no meaning
        $this->assertEquals('tmp1', $input->getValue());
        $info = $input->getInfo();
        $_FILES['file'] = array(
            'tmp_name'=>array('1'=>'tmp1'),
            'name'=>array('1'=>'img.png'),
        );
        $input->setKey(1);
        $input->processKey();
        $this->assertEquals('img.png', $info['name']);
    }
}

