<?php

/**
 * Test class for yUriScheme.
 * Generated by PHPUnit on 2011-02-18 at 06:16:58.
 */
class yUriSchemeTest extends PHPUnit_Framework_TestCase{
    /**
     * @var yUriScheme
     */
    protected $scheme;
    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(){
        $this->scheme = new yUriScheme;
    }
    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(){
        
    }
    /**
     * @todo Implement testLoadString().
     */
    public function testLoadString(){
        $this->scheme->loadString('http');
        $this->assertEquals('http:', strval($this->scheme));
        $this->scheme->clear();
        $this->assertEquals('', strval($this->scheme));
    }
}

