<?php

/**
 * Test class for yUriQuery.
 * Generated by PHPUnit on 2011-02-18 at 06:25:27.
 */
class yUriQueryTest extends PHPUnit_Framework_TestCase{
    /**
     * @var yUriQuery
     */
    protected $query;
    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(){
        $this->query = new yUriQuery;
    }
    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(){
        
    }
    /**
     * @todo Implement testGet().
     */
    public function testQuery(){
        $this->query->loadString('id=3');
        $this->assertEquals('?id=3', strval($this->query));
        $this->query->loadString('id=3&page=4');
        $this->assertEquals('?id=3&page=4', strval($this->query));
        $this->query->loadString('id=3&page=4&val');
        $this->assertEquals('?id=3&page=4&val', strval($this->query));
        $this->query->loadString('val&id=3&page=4');
        $this->assertEquals('?val&id=3&page=4', strval($this->query));
        $this->assertEquals('4', $this->query->page);
        $this->assertEquals('3', $this->query->id);
        $this->assertEquals('', $this->query->val);
        $this->query->val = '5';
        $this->query['id'] = '7';
        $this->assertEquals('5', $this->query->val);
        $this->assertEquals('7', $this->query['id']);
        $this->assertEquals('?val=5&id=7&page=4', strval($this->query));
        unset($this->query->val);
        $this->assertEquals('?id=7&page=4', strval($this->query));
        $this->assertEquals(true, isset($this->query->id));
        $this->assertEquals(true, isset($this->query['id']));
        $this->assertEquals(false, isset($this->query->val));
        $this->assertEquals(false, isset($this->query['val']));
        unset($this->query['id']);
        $this->assertEquals('?page=4', strval($this->query));
        $this->query = yUriQuery::fromString('some=that');
        $this->assertEquals('?some=that', strval($this->query));
    }
}

